{
 "title": "Аналитика товаров",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Скорость появления отзывов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(review_analysis_total{sentiment=\"positive\"}[1m]))",
     "legendFormat": "Позитивные"
    },
    {
     "expr": "sum(rate(review_analysis_total{sentiment=\"neutral\"}[1m]))",
     "legendFormat": "Нейтральные"
    },
    {
     "expr": "sum(rate(review_analysis_total{sentiment=\"negative\"}[1m]))",
     "legendFormat": "Негативные"
    }
   ]
  },
  {
   "title": "Тональность отзывов накопительным итогом",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\"})",
     "legendFormat": "Позитивные"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\"})",
     "legendFormat": "Нейтральные"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\"})",
     "legendFormat": "Негативные"
    }
   ]
  },
  {
   "title": "Хорошие черты в позитивных отзывах",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 2, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", good_quality=\"True\"})",
     "legendFormat": "Высокое качество"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", good_price=\"True\"})",
     "legendFormat": "Хорошая цена"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", good_speed_of_delivery=\"True\"})",
     "legendFormat": "Хорошая доствка"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", good_good_looking=\"True\"})",
     "legendFormat": "Хороший внешний вид"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", good_functionality=\"True\"})",
     "legendFormat": "Хороший функционал"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", good_fit_description=\"True\"})",
     "legendFormat": "Соответствует описанию"
    }
   ]
  },
  {
   "title": "Плохие черты в позитивных отзывах",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", bad_quality=\"True\"})",
     "legendFormat": "Низкое качество"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", bad_price=\"True\"})",
     "legendFormat": "Плохая цена"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", bad_speed_of_delivery=\"True\"})",
     "legendFormat": "Плохая доствка"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", bad_good_looking=\"True\"})",
     "legendFormat": "Плохой внешний вид"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", bad_functionality=\"True\"})",
     "legendFormat": "Плохая функционал"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"positive\", bad_fit_description=\"True\"})",
     "legendFormat": "Не соответствует описанию"
    }
   ]
  },
  {
   "title": "Хорошие черты в негативных отзывах",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 2, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", good_quality=\"True\"})",
     "legendFormat": "Высокое качество"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", good_price=\"True\"})",
     "legendFormat": "Хорошая цена"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", good_speed_of_delivery=\"True\"})",
     "legendFormat": "Хорошая доствка"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", good_good_looking=\"True\"})",
     "legendFormat": "Хороший внешний вид"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", good_functionality=\"True\"})",
     "legendFormat": "Хороший функционал"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", good_fit_description=\"True\"})",
     "legendFormat": "Соответствует описанию"
    }
   ]
  },
  {
   "title": "Плохие черты в негативных отзывах",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 13, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", bad_quality=\"True\"})",
     "legendFormat": "Низкое качество"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", bad_price=\"True\"})",
     "legendFormat": "Плохая цена"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", bad_speed_of_delivery=\"True\"})",
     "legendFormat": "Плохая доствка"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", bad_good_looking=\"True\"})",
     "legendFormat": "Плохой внешний вид"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", bad_functionality=\"True\"})",
     "legendFormat": "Плохая функционал"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"negative\", bad_fit_description=\"True\"})",
     "legendFormat": "Не соответствует описанию"
    }
   ]
  },
  {
   "title": "Хорошие черты в нейтральных отзывах",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 2, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", good_quality=\"True\"})",
     "legendFormat": "Высокое качество"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", good_price=\"True\"})",
     "legendFormat": "Хорошая цена"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", good_speed_of_delivery=\"True\"})",
     "legendFormat": "Хорошая доствка"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", good_good_looking=\"True\"})",
     "legendFormat": "Хороший внешний вид"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", good_functionality=\"True\"})",
     "legendFormat": "Хороший функционал"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", good_fit_description=\"True\"})",
     "legendFormat": "Соответствует описанию"
    }
   ]
  },
  {
   "title": "Плохие черты в нейтральных отзывах",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", bad_quality=\"True\"})",
     "legendFormat": "Низкое качество"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", bad_price=\"True\"})",
     "legendFormat": "Плохая цена"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", bad_speed_of_delivery=\"True\"})",
     "legendFormat": "Плохая доствка"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", bad_good_looking=\"True\"})",
     "legendFormat": "Плохой внешний вид"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", bad_functionality=\"True\"})",
     "legendFormat": "Плохая функционал"
    },
    {
     "expr": "sum(review_analysis_total{sentiment=\"neutral\", bad_fit_description=\"True\"})",
     "legendFormat": "Не соответствует описанию"
    }
   ]
  }
 ]
}